name: Run Setup Script

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  bitcoin-setup:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Check out the repository code
          
      - name: Setup, Get Block & Verify Submissions
        run: |
          # Setup Bitcoin Core
          wget https://bitcoincore.org/bin/bitcoin-core-28.0/bitcoin-28.0-x86_64-linux-gnu.tar.gz
          tar -xzvf bitcoin-28.0-x86_64-linux-gnu.tar.gz
          sudo ln -s $PWD/bitcoin-28.0/bin/* /usr/local/bin/

          mkdir -p ~/.bitcoin
          echo "signet=1" >> ~/.bitcoin/bitcoin.conf
          echo "rpcconnect=165.22.121.70" >> ~/.bitcoin/bitcoin.conf
          echo "rpcuser=btrustbuildersrpc" >> ~/.bitcoin/bitcoin.conf
          echo "rpcpassword=btrustbuilderspass" >> ~/.bitcoin/bitcoin.conf

          # Verify block is accessible
          echo "Fetching block chain info..."
          bitcoin-cli -signet getblockchaininfo
      
          # Run and verify 01.sh
          chmod +x submission/01.sh
          HASH=$(submission/01.sh)
          EXPECTED=000000b024f11595795f0be5974229f786df389c8b92e92b61890e9e3c6b8d8a
          if [[ "$HASH" == "$EXPECTED" ]]; then
            echo "✅ Success: Verify Hash Block passed!"
          else
            echo "❌ Error: Verify Hash Block failed!"
            exit 1
          fi
      
          # 02.sh - Verify Input Count
          chmod +x submission/02.sh
          COUNT=$(submission/02.sh)
          if [[ "$COUNT" == "442" ]]; then
            echo "✅ Success: Input Count verification passed!"
          else
            echo "❌ Error: Input Count verification failed!"
            exit 1
          fi
      
          # 03.sh - Verify Transaction
          chmod +x submission/03.sh
          TX=$(submission/03.sh)
          EXPECTED=0e302b600d32b86c3362647f422e5605165a1e5c89c760d0d972e102f390c84e
          if [[ "$TX" == "$EXPECTED" ]]; then
            echo "✅ Success: Transaction verification passed!"
          else
            echo "❌ Error: Transaction verification failed!"
            exit 1
          fi
      
          # 04.sh - Verify Public Key Signer
          chmod +x submission/04.sh
          PUBKEY=$(submission/04.sh)
          EXPECTED_OUTPUT=02c6c9306ade30f9711c9503cdaa94094efc025acb9be7845acc49e1cb475952c6
          if [[ "$PUBKEY" == "$EXPECTED_OUTPUT" ]]; then
            echo "✅ Success: Public Key Signer verification passed!"
          else
            echo "❌ Error: Public Key Signer verification failed!"
            exit 1
          fi
      
          # 05.sh - Verify TX Fee
          chmod +x submission/05.sh
          FEE=$(submission/05.sh)
          if [[ "$FEE" == "696" ]]; then
            echo "✅ Success: TX Fee (05.sh) verification passed!"
          else
            echo "❌ Error: TX Fee (05.sh) verification failed!"
            exit 1
          fi
      
          # 06.sh - Verify TX Fee (again)
          chmod +x submission/06.sh
          FEE=$(submission/06.sh)
          if [[ "$FEE" == "696" ]]; then
            echo "✅ Success: TX Fee (06.sh) verification passed!"
          else
            echo "❌ Error: TX Fee (06.sh) verification failed!"
            exit 1
          fi
      
          # 07.sh - Verify Coinbase TX
          chmod +x submission/07.sh
          COINBASE=$(submission/07.sh)
          EXPECTED_OUTPUT=7ab200e41b53d974f757535c01a715aae6b1322a30753c1d2b0ea201500bc060
          if [[ "$COINBASE" == "$EXPECTED_OUTPUT" ]]; then
            echo "✅ Success: Coinbase TX verification passed!"
          else
            echo "❌ Error: Coinbase TX verification failed!"
            exit 1
          fi
      
          # 08.sh - Verify TX Block Height
          chmod +x submission/08.sh
          HEIGHT=$(submission/08.sh)
          if [[ "$HEIGHT" == "243859" ]]; then
            echo "✅ Success: TX Block Height verification passed!"
          else
            echo "❌ Error: TX Block Height verification failed!"
            exit 1
          fi


          ## FINAL TASK

          # Read wallet name and verify GitHub profile
          if [ ! -s submission/wallet.txt ]; then
              echo "❌ Error: wallet.txt is empty or missing."
              exit 1
          fi

          WALLET=$(cat submission/wallet.txt | tr -d '\n')
          echo "wallet=$WALLET" >> $GITHUB_OUTPUT
      
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://github.com/$WALLET)
          if [[ "$STATUS_CODE" == "200" ]]; then
            echo "✅ GitHub profile exists: https://github.com/$WALLET"
          else
            echo "❌ GitHub profile not found for wallet name '$WALLET'"
            exit 1
          fi

          # Verify native SegWit address exists
          ADDRESS=$(cat submission/address.txt)
          if [[ $ADDRESS == "tb1"* ]]; then
            echo "✅ Native SegWit address is valid: $ADDRESS"
          else
            echo "❌ Invalid SegWit address: $ADDRESS"
            exit 1
          fi