name: Run Setup Script

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  bitcoin-setup:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Check out the repository code
          
      - name: Setup, Get Block & Verify Submissions
        run: |
          # Setup Bitcoin Core
          wget https://bitcoincore.org/bin/bitcoin-core-28.0/bitcoin-28.0-x86_64-linux-gnu.tar.gz
          tar -xzvf bitcoin-28.0-x86_64-linux-gnu.tar.gz
          sudo ln -s $PWD/bitcoin-28.0/bin/* /usr/local/bin/

          mkdir -p ~/.bitcoin
          echo "signet=1" >> ~/.bitcoin/bitcoin.conf
          echo "rpcconnect=165.22.121.70" >> ~/.bitcoin/bitcoin.conf
          echo "rpcuser=btrustbuildersrpc" >> ~/.bitcoin/bitcoin.conf
          echo "rpcpassword=btrustbuilderspass" >> ~/.bitcoin/bitcoin.conf

          # Verify block is accessible
          echo "Fetching block chain info..."
          bitcoin-cli -signet getblockchaininfo
      
          # Run and verify 01.sh
          chmod +x submission/01.sh
          HASH=$(submission/01.sh)
          EXPECTED=000000b024f11595795f0be5974229f786df389c8b92e92b61890e9e3c6b8d8a
          if [[ "$HASH" == "$EXPECTED" ]]; then
            echo "✅ Success: Verify Hash Block passed!"
          else
            echo "❌ Error: Verify Hash Block failed!"
            exit 1
          fi
      
          # 02.sh - Verify Input Count
          chmod +x submission/02.sh
          COUNT=$(submission/02.sh)
          if [[ "$COUNT" == "442" ]]; then
            echo "✅ Success: Input Count verification passed!"
          else
            echo "❌ Error: Input Count verification failed!"
            exit 1
          fi
      
          # 03.sh - Verify Transaction
          chmod +x submission/03.sh
          TX=$(submission/03.sh)
          EXPECTED=0e302b600d32b86c3362647f422e5605165a1e5c89c760d0d972e102f390c84e
          if [[ "$TX" == "$EXPECTED" ]]; then
            echo "✅ Success: Transaction verification passed!"
          else
            echo "❌ Error: Transaction verification failed!"
            exit 1
          fi
      
          # 04.sh - Verify Public Key Signer
          chmod +x submission/04.sh
          PUBKEY=$(submission/04.sh)
          EXPECTED_OUTPUT=02c6c9306ade30f9711c9503cdaa94094efc025acb9be7845acc49e1cb475952c6
          if [[ "$PUBKEY" == "$EXPECTED_OUTPUT" ]]; then
            echo "✅ Success: Public Key Signer verification passed!"
          else
            echo "❌ Error: Public Key Signer verification failed!"
            exit 1
          fi
      
          # 05.sh - Verify TX Fee
          chmod +x submission/05.sh
          FEE=$(submission/05.sh)
          if [[ "$FEE" == "696" ]]; then
            echo "✅ Success: TX Fee (05.sh) verification passed!"
          else
            echo "❌ Error: TX Fee (05.sh) verification failed!"
            exit 1
          fi
      
          # 06.sh - Verify TX Fee (again)
          chmod +x submission/06.sh
          FEE=$(submission/06.sh)
          if [[ "$FEE" == "696" ]]; then
            echo "✅ Success: TX Fee (06.sh) verification passed!"
          else
            echo "❌ Error: TX Fee (06.sh) verification failed!"
            exit 1
          fi
      
          # 07.sh - Verify Coinbase TX
          chmod +x submission/07.sh
          COINBASE=$(submission/07.sh)
          EXPECTED_OUTPUT=7ab200e41b53d974f757535c01a715aae6b1322a30753c1d2b0ea201500bc060
          if [[ "$COINBASE" == "$EXPECTED_OUTPUT" ]]; then
            echo "✅ Success: Coinbase TX verification passed!"
          else
            echo "❌ Error: Coinbase TX verification failed!"
            exit 1
          fi
      
          # 08.sh - Verify TX Block Height
          chmod +x submission/08.sh
          HEIGHT=$(submission/08.sh)
          if [[ "$HEIGHT" == "243859" ]]; then
            echo "✅ Success: TX Block Height verification passed!"
          else
            echo "❌ Error: TX Block Height verification failed!"
            exit 1
          fi


          ## FINAL TASK

          # Read wallet name and verify GitHub profile
          if [ ! -s submission/wallet.txt ]; then
              echo "❌ Error: wallet.txt is empty or missing."
              exit 1
          fi

          WALLET=$(cat submission/wallet.txt | tr -d '\n')
          echo "wallet=$WALLET" >> $GITHUB_OUTPUT
      
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://github.com/$WALLET)
          if [[ "$STATUS_CODE" == "200" ]]; then
            echo "✅ GitHub profile exists: https://github.com/$WALLET"
          else
            echo "❌ GitHub profile not found for wallet name '$WALLET'"
            exit 1
          fi

          # Verify native SegWit address exists
          if [ ! -s submission/address.txt ]; then
              echo "❌ Error: address.txt is empty or missing."
              exit 1
          fi

          ADDRESS=$(cat submission/address.txt)
          if [[ $ADDRESS == "tb1"* ]]; then
            echo "✅ Native SegWit address is valid: $ADDRESS"
          else
            echo "❌ Invalid SegWit address: $ADDRESS"
            exit 1
          fi

          # Verify transaction-1.txt (funding tx)
          if [[ ! -s submission/transaction-1.txt ]]; then
              echo "❌ Error: transaction-1.txt is empty or missing."
              exit 1
          fi
          TX1=$(cat submission/transaction-1.txt)
          if bitcoin-cli -signet -rpcwallet=$WALLET getrawtransaction $TX1 &> /dev/null; then
            echo "✅ Funding transaction exists: $TX1"
          else
            echo "❌ Funding transaction not found: $TX1"
            exit 1
          fi


          # Verify block-1.txt
          if [[ ! -s submission/block-1.txt ]]; then
              echo "❌ Error: block-1.txt is empty or missing."
              exit 1
          fi
          BLOCK1=$(cat submission/block-1.txt | tr -d '\n')
          TXS1=$(bitcoin-cli -signet getblock $BLOCK1 | jq -r '.tx[]')
          if echo "$TXS1" | grep -xq "$TX1"; then
              echo "✅ transaction-1 is included in block-1."
          else
              echo "❌ transaction-1 not found in block-1."
              exit 1
          fi

          # Verify block-1.txt and coinbase-1.txt
          BLOCK=$(cat submission/block-1.txt)
          COINBASE=$(cat submission/coinbase-1.txt)
          if bitcoin-cli -signet getblock $BLOCK | grep -q "$COINBASE"; then
            echo "✅ Coinbase TX $COINBASE found in block $BLOCK"
          else
            echo "❌ Coinbase TX $COINBASE NOT found in block $BLOCK"
            exit 1
          fi


          # Verify transaction-2.txt (spend tx)
          TXID=$(cat submission/transaction-2.txt)
          if bitcoin-cli -signet -rpcwallet=$WALLET getrawtransaction $TXID &> /dev/null; then
            echo "✅ Spend transaction exists: $TXID"
          else
            echo "❌ Spend transaction not found: $TXID"
            exit 1
          fi
          

          # Verify block-2.txt and coinbase-2.txt
          BLOCK=$(cat submission/block-2.txt)
          COINBASE=$(cat submission/coinbase-2.txt)
          if bitcoin-cli -signet getblock $BLOCK | grep -q "$COINBASE"; then
            echo "✅ Coinbase TX $COINBASE found in block $BLOCK"
          else
            echo "❌ Coinbase TX $COINBASE NOT found in block $BLOCK"
            exit 1
          fi


          # Verify multisig address
          ADDRESS=$(cat submission/multisig-address.txt)
          if [[ $ADDRESS == "2"* ]]; then
            echo "✅ Multisig address look valid."
          else
            echo "❌ Invalid multisig address"
            exit 1
          fi

          # Verify multisig redeem script
          REDEEM=$(cat submission/multisig-redeem.txt)
          if [[ $REDEEM =~ ^[0-9a-fA-F]+$ ]]; then
            echo "✅ Multisig redeem script look valid."
          else
            echo "❌ Invalid multisig redeem script"
            exit 1
          fi

          # Verify multisig transaction and block
          TXID=$(cat submission/multisig-transaction.txt)
          BLOCK=$(cat submission/multisig-block.txt)
          COINBASE=$(cat submission/multisig-coinbase.txt)
          if bitcoin-cli -signet getrawtransaction $TXID &> /dev/null; then
            echo "✅ Multisig funding transaction exists: $TXID"
          else
            echo "❌ Multisig funding transaction not found"
            exit 1
          fi
          if bitcoin-cli -signet getblock $BLOCK | grep -q "$COINBASE"; then
            echo "✅ Multisig coinbase TX $COINBASE found in block $BLOCK"
          else
            echo "❌ Multisig coinbase TX $COINBASE not found in block $BLOCK"
            exit 1
          fi